name: flutter_airpods
description: A Flutter plugin project to get information from AirPods.
version: 1.0.1
repository: https://github.com/lucas-goldner/flutter_airpods
issue_tracker: https://github.com/lucas-goldner/flutter_airpods/issues

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterAirpodsPlugin
